[FIX][sale_stock_picking_return_invoice]:Corrección calculo devoluciones
TRESCLOUD/account-invoicing pull request #12
Opened 2018-01-22 20:06 UTC by vsalazar2017

2018-01-23 03:21 UTC, pepetreshere requested changes
Favor trabajar en los cambios, especialmente en los help.

No puedo revisar la lógica de la programación sin los help.

2018-01-23 03:21 UTC, pepetreshere commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +    def _get_to_invoice_qty(self):
para que se cambia el esquema de nombres?

2018-01-23 03:21 UTC, pepetreshere commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +    qty_to_refund = fields.Float(compute='_get_to_invoice_qty', string='Qty to Refund', copy=False, default=0.0,
porque no mantener el mismo esquema de nombres de metodos, como el _compute_qty_to_invoice

2018-01-23 03:21 UTC, pepetreshere commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +    qty_delivered = fields.Float(help='Cantidad total entregada al cliente.')
Estos help parecen labels, faavor poner helps en este formato:
"Cantidad total entregada al cliente, se calcula como la suma/resta/otraoperacion entre las facturas emitidas y las notas de crédito emitidas"... indicando la operación y los documentos involucrados.

Este tema ya fue  pedido verbalmente, y un help que es igual al label no aporta

2018-01-23 03:21 UTC, pepetreshere commented on sale_stock_picking_return_invoicing/views/sale_view.xml
> +			</xpath>
Evaluar remover estos campos de la vista, hacen mas dificil de leer la venta, reunete un momento conmigo para evaluar criterios

2018-01-23 14:27 UTC, vsalazar2017 commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +    def _get_to_invoice_qty(self):
por que ese método es utilizado por el core

2018-01-23 14:29 UTC, vsalazar2017 commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +    qty_to_refund = fields.Float(compute='_get_to_invoice_qty', string='Qty to Refund', copy=False, default=0.0,
utilizamos el mismo método del core para realizar el calculo, el sale el metodo se llama _get_to_invoice_qty

2018-01-23 14:36 UTC, vsalazar2017 commented on sale_stock_picking_return_invoicing/models/sale_order.py
> +                if line.product_id.invoice_policy == 'order':
pues esta en base al core, me pareció buena idea ocupar las políticas de la factura por cantidades recibidas, así utilizamos el método de calculo para las dos políticas existentes, en el core.

2018-01-29 18:07 UTC, vsalazar2017 commented on sale_stock_picking_return_invoicing/models/sale_order.py
>                      qty = (line.product_uom_qty - line.qty_returned) - (line.qty_invoiced - line.qty_refunded)
mantenemos la lógica ya  que si utilizamos el max como se sugirió  seria mejor utilizar la cantidad entregada,

2018-02-14 21:15 UTC, pepetreshere approved these changes

2018-02-14 21:17 UTC, merged